# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 21:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0005_auto_20161218_1617'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Friend_list',
            new_name='Friend',
        ),
    ]
